
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int aboutEachAttr = 37;
  public static final int bagIdAttr = 49;
  public static final int NSname = 68;
  public static final int resource = 32;
  public static final int RDFAEP = 42;
  public static final int SEMI = 2;
  public static final int inlineItem = 74;
  public static final int RDFDESCR = 40;
  public static final int KRSQBKT = 47;
  public static final int COMMA = 44;
  public static final int QOT = 46;
  public static final int about = 12;
  public static final int RDFDATATYPE = 63;
  public static final int RPAREN = 8;
  public static final int RDFR = 59;
  public static final int KLSQBKT = 25;
  public static final int aboutEachPrefix = 79;
  public static final int UNDER = 19;
  public static final int LPAREN = 7;
  public static final int IDsymbol = 67;
  public static final int referencedItem = 73;
  public static final int RDFNODEID = 60;
  public static final int idRefAttr = 55;
  public static final int value = 56;
  public static final int RDFLI = 39;
  public static final int KLRQBKT = 26;
  public static final int ResumeTag = 10;
  public static final int NUMBER = 81;
  public static final int FULL = 30;
  public static final int WS = 48;
  public static final int BRBRKT = 28;
  public static final int SLASH = 15;
  public static final int PLUS = 3;
  public static final int nodeID = 33;
  public static final int Description = 34;
  public static final int EQUAL = 38;
  public static final int typedNode = 52;
  public static final int alternative = 71;
  public static final int OGT = 22;
  public static final int RDFRESOURCE = 62;
  public static final int name = 57;
  public static final int bagID = 76;
  public static final int anyString = 65;
  public static final int OGE = 23;
  public static final int bag = 70;
  public static final int URI = 66;
  public static final int RDFPARSETYPE = 64;
  public static final int EOF = 0;
  public static final int OPSL = 16;
  public static final int MINUS = 4;
  public static final int AnyTag = 80;
  public static final int container = 35;
  public static final int idAboutAttr = 36;
  public static final int property = 51;
  public static final int OLT = 21;
  public static final int KRBRKT = 29;
  public static final int member = 72;
  public static final int error = 1;
  public static final int propAttr = 50;
  public static final int EXCL = 18;
  public static final int typeName = 54;
  public static final int ID = 11;
  public static final int EndTag = 13;
  public static final int StartTag = 9;
  public static final int OLE = 45;
  public static final int sequence = 69;
  public static final int RDFABOUT = 41;
  public static final int RDFABOUTE = 61;
  public static final int QUEST = 17;
  public static final int KLBRKT = 27;
  public static final int ORSHIFT = 24;
  public static final int ARON = 14;
  public static final int dataType = 75;
  public static final int aboutEach = 78;
  public static final int propName = 53;
  public static final int RDFBAGID = 43;
  public static final int RDFID = 58;
  public static final int Terms = 77;
  public static final int OLSHIFT = 20;
  public static final int UMINUS = 5;
  public static final int parseType = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "StartTag",
  "ResumeTag",
  "ID",
  "about",
  "EndTag",
  "ARON",
  "SLASH",
  "OPSL",
  "QUEST",
  "EXCL",
  "UNDER",
  "OLSHIFT",
  "OLT",
  "OGT",
  "OGE",
  "ORSHIFT",
  "KLSQBKT",
  "KLRQBKT",
  "KLBRKT",
  "BRBRKT",
  "KRBRKT",
  "FULL",
  "parseType",
  "resource",
  "nodeID",
  "Description",
  "container",
  "idAboutAttr",
  "aboutEachAttr",
  "EQUAL",
  "RDFLI",
  "RDFDESCR",
  "RDFABOUT",
  "RDFAEP",
  "RDFBAGID",
  "COMMA",
  "OLE",
  "QOT",
  "KRSQBKT",
  "WS",
  "bagIdAttr",
  "propAttr",
  "property",
  "typedNode",
  "propName",
  "typeName",
  "idRefAttr",
  "value",
  "name",
  "RDFID",
  "RDFR",
  "RDFNODEID",
  "RDFABOUTE",
  "RDFRESOURCE",
  "RDFDATATYPE",
  "RDFPARSETYPE",
  "anyString",
  "URI",
  "IDsymbol",
  "NSname",
  "sequence",
  "bag",
  "alternative",
  "member",
  "referencedItem",
  "inlineItem",
  "dataType",
  "bagID",
  "Terms",
  "aboutEach",
  "aboutEachPrefix",
  "AnyTag",
  "NUMBER"
  };
}

